### ISSUE TITLE
zmk shields?

### ISSUE THREAD

**Issue by otosky** [jimmerricks/bugs#2]
do you have zmk shields available for these boards anywhere?

love these designs and had a couple copies of the Midge made in a recent JLCPCB order of assorted things.  just wanted to see if you already had a shield before I cobble one together from the traces 😄

**Comment by jimmerricks** [comment]
Hey, great that you are interested in the Bugs! I have some ZMK shield configs for these keyboards available here: https://seafile.4nmo.com/d/b173c5f21e3045a2807b/. If you need any help compiling, let me know. Are you on Discord?

**Comment by steevelefort** [comment]
Hi,
The previous link doesn’t work anymore. Do you still have this file ?
