### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by jonathf** [jimmerricks/bugs#3]
Hi!

The design of these keyboards are really great and I am considering having them printed. I am familiar with soldering, but only on store bought kits. I was wondering if you could answer some questions regarding the Flea.

1. Does it support Nice!nano and zmk?
2. Is the sockets designed for choc v1 with choc spacing?
3. Are there case designs available?
4. Does it support power switch? If so, what kind?
5. Anything out of the ordenary with these designs I should be aware of?

**Comment by jimmerricks** [comment]
Hi. Thanks for your interest in the Bugs.

1. Yes
2. Yes
3. No. But someone has made some. Details are in [my channel](https://discord.com/channels/714176584269168732/912348297107214378) on [the Absolem Club Discord server](https://discord.gg/w7VMtFzDGY): https://discord.com/channels/714176584269168732/912348297107214378/1069273304696901692. You could always ask them for the files.
4. Yes. It is the seven pin SMD switch sold by a bunch of ergo stores.
5. They do not have a reset switch. If you want to flash them you need to short the reset and ground pins on the n!n.

The best place to get help with my designs is on the Discord server linked above. Good luck with your build.
